FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci && \
    addgroup -g 1001 -S nodejs && \
    adduser -S nextjs -u 1001 && \
    chown -R nextjs:nodejs /app

USER nextjs

COPY --chown=nextjs:nodejs . .

ARG FRONTEND_PORT
ARG BACKEND_PORT
ARG BACKEND_HOST
ENV NEXT_PUBLIC_FRONTEND_PORT=${FRONTEND_PORT}
ENV NEXT_PUBLIC_BACKEND_PORT=${BACKEND_PORT}
ENV NEXT_PUBLIC_BACKEND_HOST=${BACKEND_HOST}

EXPOSE ${FRONTEND_PORT}

CMD ["sh", "-c", "npm run dev -- -p ${NEXT_PUBLIC_FRONTEND_PORT}"]